#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-bio3d
Version  : 2.3.4
Release  : 10
URL      : https://cran.r-project.org/src/contrib/bio3d_2.3-4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/bio3d_2.3-4.tar.gz
Summary  : Biological Structure Analysis
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-bio3d-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-igraph
Requires: R-markdown
BuildRequires : R-Rcpp
BuildRequires : R-igraph
BuildRequires : R-markdown
BuildRequires : buildreq-R
BuildRequires : pkgconfig(zlib)
BuildRequires : zlib-dev

%description
# Documentation
The Bio3D package for structural bioinformatics consists of sets of functions for:
- <a href="#Input/Output:">input/output</a>,
- <a href="#Sequence Analysis:">sequence analysis</a>,
- <a href="#Structure Analysis:">structure analysis</a>,
- <a href="#Trajectory Analysis:">simulation analysis</a>,
- <a href="#Normal Mode Analysis:">normal mode analysis</a>,
- <a href="#Correlation Network Analysis:"> correlation network analysis</a>,
- <a href="#Utilities:">format conversion and data manipulation</a>, and
- <a href="#Graphics:">graphics and visualization.</a>.
Major functions are listed below with links to further documentation that includes example code and results.

%package lib
Summary: lib components for the R-bio3d package.
Group: Libraries

%description lib
lib components for the R-bio3d package.


%prep
%setup -q -c -n bio3d

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552719877

%install
export SOURCE_DATE_EPOCH=1552719877
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bio3d
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bio3d
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bio3d
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc  bio3d || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/bio3d/CITATION
/usr/lib64/R/library/bio3d/DESCRIPTION
/usr/lib64/R/library/bio3d/INDEX
/usr/lib64/R/library/bio3d/Meta/Rd.rds
/usr/lib64/R/library/bio3d/Meta/data.rds
/usr/lib64/R/library/bio3d/Meta/demo.rds
/usr/lib64/R/library/bio3d/Meta/features.rds
/usr/lib64/R/library/bio3d/Meta/hsearch.rds
/usr/lib64/R/library/bio3d/Meta/links.rds
/usr/lib64/R/library/bio3d/Meta/nsInfo.rds
/usr/lib64/R/library/bio3d/Meta/package.rds
/usr/lib64/R/library/bio3d/Meta/vignette.rds
/usr/lib64/R/library/bio3d/NAMESPACE
/usr/lib64/R/library/bio3d/NEWS
/usr/lib64/R/library/bio3d/R/bio3d
/usr/lib64/R/library/bio3d/R/bio3d.rdb
/usr/lib64/R/library/bio3d/R/bio3d.rdx
/usr/lib64/R/library/bio3d/data/Rdata.rdb
/usr/lib64/R/library/bio3d/data/Rdata.rds
/usr/lib64/R/library/bio3d/data/Rdata.rdx
/usr/lib64/R/library/bio3d/demo/md.R
/usr/lib64/R/library/bio3d/demo/nma.R
/usr/lib64/R/library/bio3d/demo/pca.R
/usr/lib64/R/library/bio3d/demo/pdb.R
/usr/lib64/R/library/bio3d/doc/bio3d_vignettes.Rmd
/usr/lib64/R/library/bio3d/doc/bio3d_vignettes.html
/usr/lib64/R/library/bio3d/doc/index.html
/usr/lib64/R/library/bio3d/examples/1dpx.pdb
/usr/lib64/R/library/bio3d/examples/1hel.pdb
/usr/lib64/R/library/bio3d/examples/aspirin.mol2
/usr/lib64/R/library/bio3d/examples/crambin.inpcrd
/usr/lib64/R/library/bio3d/examples/crambin.prmtop
/usr/lib64/R/library/bio3d/examples/hivp.dcd
/usr/lib64/R/library/bio3d/examples/hivp.pdb
/usr/lib64/R/library/bio3d/examples/hivp_xray.fa
/usr/lib64/R/library/bio3d/examples/kif1a.fa
/usr/lib64/R/library/bio3d/examples/test.pdb
/usr/lib64/R/library/bio3d/examples/transducin.fa
/usr/lib64/R/library/bio3d/help/AnIndex
/usr/lib64/R/library/bio3d/help/aliases.rds
/usr/lib64/R/library/bio3d/help/bio3d.rdb
/usr/lib64/R/library/bio3d/help/bio3d.rdx
/usr/lib64/R/library/bio3d/help/paths.rds
/usr/lib64/R/library/bio3d/html/00Index.html
/usr/lib64/R/library/bio3d/html/R.css
/usr/lib64/R/library/bio3d/matrices/bio3d.mat
/usr/lib64/R/library/bio3d/matrices/blosum62.mat
/usr/lib64/R/library/bio3d/matrices/custom.mat
/usr/lib64/R/library/bio3d/matrices/emboss_properties.mat
/usr/lib64/R/library/bio3d/matrices/pam30.mat
/usr/lib64/R/library/bio3d/matrices/properties.mat
/usr/lib64/R/library/bio3d/matrices/similarity.mat
/usr/lib64/R/library/bio3d/staticdocs/index.r
/usr/lib64/R/library/bio3d/tests/testthat.R
/usr/lib64/R/library/bio3d/tests/testthat/test-aa2mass.R
/usr/lib64/R/library/bio3d/tests/testthat/test-aanma.R
/usr/lib64/R/library/bio3d/tests/testthat/test-aanma.pdbs.R
/usr/lib64/R/library/bio3d/tests/testthat/test-atom.select.R
/usr/lib64/R/library/bio3d/tests/testthat/test-atom2mass.R
/usr/lib64/R/library/bio3d/tests/testthat/test-clean.pdb.R
/usr/lib64/R/library/bio3d/tests/testthat/test-cmap.R
/usr/lib64/R/library/bio3d/tests/testthat/test-cna.R
/usr/lib64/R/library/bio3d/tests/testthat/test-core.find.R
/usr/lib64/R/library/bio3d/tests/testthat/test-dccm.R
/usr/lib64/R/library/bio3d/tests/testthat/test-deformation.R
/usr/lib64/R/library/bio3d/tests/testthat/test-dssp.R
/usr/lib64/R/library/bio3d/tests/testthat/test-fitting.R
/usr/lib64/R/library/bio3d/tests/testthat/test-get.pdb.R
/usr/lib64/R/library/bio3d/tests/testthat/test-gnm.R
/usr/lib64/R/library/bio3d/tests/testthat/test-mol2.R
/usr/lib64/R/library/bio3d/tests/testthat/test-nma.R
/usr/lib64/R/library/bio3d/tests/testthat/test-nma.pdbs.R
/usr/lib64/R/library/bio3d/tests/testthat/test-overlap.R
/usr/lib64/R/library/bio3d/tests/testthat/test-pca.R
/usr/lib64/R/library/bio3d/tests/testthat/test-pdb.annotate.R
/usr/lib64/R/library/bio3d/tests/testthat/test-pdbsplit.R
/usr/lib64/R/library/bio3d/tests/testthat/test-read.all.R
/usr/lib64/R/library/bio3d/tests/testthat/test-read.ncdf.R
/usr/lib64/R/library/bio3d/tests/testthat/test-read.pdb.R
/usr/lib64/R/library/bio3d/tests/testthat/test-rmsd.R
/usr/lib64/R/library/bio3d/tests/testthat/test-seqaln.R
/usr/lib64/R/library/bio3d/tests/testthat/test-vector-funs.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/bio3d/libs/bio3d.so
/usr/lib64/R/library/bio3d/libs/bio3d.so.avx2
